spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/db/H2/anisdb/data;
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jwt:
    secret: QW5pc1Byb2plY3RKd3RTZWNyZXRLZXk=
  password : 1234
  data:
    mongodb:
      uri: mongodb://localhost:27017/ANIS


logging:
  level:
    org:
      springframework:
        security=DEBUG:
