spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/db/H2/anisdb/data;
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    # Hibernate 스키마 생성이 수행된 후에,데이터베이스를 채우기 위해
    # 추가 data.sql 실행되도록 보장해주는 코드
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jwt:
    secret: QW5pc1Byb2plY3RKd3RTZWNyZXRLZXk=
  password : 1234
  data:
    mongodb:
      uri: mongodb://localhost:27017/ANIS
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  # mode: always data.sql 에 sql 문을 자동으로 읽어줘서 데이터 삽입
# mode: never data.sql 에 sql 문을 읽지않음
# 더미데이터를 맨 처음에 넣을때 always로 바꿔서 데이터를 넣어준 후,
# 넣고 나서 sql: init: mode: never 로 바꿔주기
  sql:
    init:
      mode: never
logging:
  level:
    org:
      springframework:
        security=DEBUG:
# firebase
fcm:
  firebase_config_path: firebase/fcmCertification.json